#!/usr/bin/env python3
"""Cerca nel workspace i SEGNALI strutturali che suggeriscono un function hook,
anche dove nessuna regola è scritta: file todo, segreti, file autogenerati,
changelog, deploy legati al push, lockfile, database, server MCP, code pendenti.

Solo stdlib, sola lettura. Euristico: produce candidati con evidenza (path);
la decisione finale la fa l'agente con l'utente. Ogni segnale è documentato in
references/opportunity-signals.md (stesso `signal` id).

Uso:
  python3 find_opportunities.py                      # cwd
  python3 find_opportunities.py --root ~/proj --depth 4 --out tmp/hooks-audit/opportunities.json --md
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

SKIP_DIRS = {
    "node_modules", ".git", ".venv", "venv", "__pycache__", "dist", "build", "target", "vendor",
    ".next", ".cache", ".pytest_cache", ".mypy_cache", ".ruff_cache", "tmp", "worktrees", ".worktrees",
    "site-packages", ".tox", "coverage", ".idea", ".vscode",
}
MAX_HEAD_BYTES = 2048

# --- pattern per nome file -------------------------------------------------
TODO_NAMES = re.compile(r"^(todo|todos|to-do|tasks?|inbox|backlog|next-actions?)([-_.][\w-]+)?\.md$", re.I)
CHECKBOX = re.compile(r"^\s*[-*]\s+\[[ xX]\]\s", re.M)
NUMBERED = re.compile(r"^\d+\.\s", re.M)
SECRET_NAMES = re.compile(
    r"^(\.env(\..+)?|.*credentials.*\.json|.*service[-_]account.*\.json|.*token.*\.json|.*\.pem|.*\.key|id_(rsa|ed25519)(\.pub)?|.*secrets?\.(ya?ml|json|toml))$",
    re.I,
)
SECRET_EXAMPLE = re.compile(r"\.(example|sample|template|dist)$|example", re.I)
SECRET_DIRS = {".secrets", "secrets", ".credentials", "credentials"}
GENERATED_WORDS = re.compile(
    r"auto-?generated|auto-?generat[oa]|auto-?rigenerat[oa]|do not edit|don't edit|non editare|non modificare a mano|generated by|@generated",
    re.I,
)
GENERATED_MARK = re.compile(r"<!--\s*(?:generated|auto|TREE:START)|TREE:START")
COMMENT_LINE = re.compile(r"^\s*(#|//|/\*|\*|<!--|--|;|%)")


def looks_generated(h: str, is_markdown: bool) -> bool:
    """Marker solo in righe di commento (o nelle prime 3 righe di un markdown): la prosa non conta."""
    if GENERATED_MARK.search(h):
        return True
    lines = h.splitlines()[:12]
    for i, line in enumerate(lines):
        if not GENERATED_WORDS.search(line):
            continue
        if COMMENT_LINE.match(line) or (is_markdown and i < 3):
            return True
    return False
CHANGELOG_NAMES = re.compile(r"^(changelog|history|changes)(\.md|\.txt)?$", re.I)
GEN_SCRIPT_NAMES = re.compile(r"(changelog|generate|regen|update[-_](docs|tree|index|schema)|build[-_]docs)", re.I)
DEPLOY_FILES = {
    "netlify.toml": "Netlify", "vercel.json": "Vercel", "fly.toml": "Fly.io", "render.yaml": "Render",
    "wrangler.toml": "Cloudflare", "Procfile": "Heroku", "app.yaml": "App Engine", "serverless.yml": "Serverless",
    "firebase.json": "Firebase", ".gitmodules": "git submodule (repo separata, deploy proprio)",
}
LOCKFILES = {
    "pnpm-lock.yaml": ("pnpm", r"\bnpm\b|\byarn\b"), "yarn.lock": ("yarn", r"\bnpm\b|\bpnpm\b"),
    "bun.lockb": ("bun", r"\bnpm\b|\bnpx\b"), "bun.lock": ("bun", r"\bnpm\b|\bnpx\b"),
    "package-lock.json": ("npm", r"\bpnpm\b|\byarn\b"),
}
PY_ENV_FILES = {
    "uv.lock": "uv run / .venv/bin/python", "poetry.lock": "poetry run python", "Pipfile.lock": "pipenv run python",
    "environment.yml": "conda env (vedi name: nel file)", ".python-version": "interprete pyenv indicato nel file",
}
DB_EXT = {".db", ".sqlite", ".sqlite3", ".duckdb"}
MARKER_NAMES = re.compile(r"(last[-_]run|\.last|pending|queue|inbox)", re.I)
FORMATTER_FILES = {
    ".prettierrc": "prettier", ".prettierrc.json": "prettier", "prettier.config.js": "prettier", "prettier.config.mjs": "prettier",
    "biome.json": "biome", "ruff.toml": "ruff", ".ruff.toml": "ruff", ".eslintrc.json": "eslint", "eslint.config.js": "eslint",
    "eslint.config.mjs": "eslint", ".editorconfig": None, "rustfmt.toml": "rustfmt", ".golangci.yml": "golangci-lint",
}
GIT_CONVENTION_FILES = {
    ".gitmessage": "template commit", "commitlint.config.js": "commitlint", "commitlint.config.cjs": "commitlint",
    ".commitlintrc.json": "commitlint", ".pre-commit-config.yaml": "pre-commit", ".husky": "husky",
    "PULL_REQUEST_TEMPLATE.md": "template PR", "CODEOWNERS": "CODEOWNERS",
}
OTHER_AGENT_FILES = ["AGENTS.md", ".cursorrules", ".cursor", ".github/copilot-instructions.md", ".agents", ".windsurfrules", "GEMINI.md"]
DESTRUCTIVE_TOOL = re.compile(r"(delete|trash|remove|destroy|purge|drop|send|publish|deploy|pay|charge|transfer|revoke)", re.I)


def head(path: Path) -> str:
    try:
        with path.open("rb") as fh:
            return fh.read(MAX_HEAD_BYTES).decode("utf-8", errors="replace")
    except OSError:
        return ""


def read_text(path: Path, limit: int = 200_000) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")[:limit]
    except OSError:
        return ""


def walk(root: Path, depth: int):
    root_depth = len(root.parts)
    for dirpath, dirnames, filenames in os.walk(root):
        d = Path(dirpath)
        dirnames[:] = [x for x in dirnames if x not in SKIP_DIRS and not (x.startswith(".") and x not in {".claude", ".github", ".secrets", ".credentials", ".agents", ".cursor", ".husky"})]
        if len(d.parts) - root_depth >= depth:
            dirnames[:] = []
        yield d, dirnames, filenames


class Finder:
    def __init__(self, root: Path, depth: int):
        self.root = root
        self.depth = depth
        self.out: list[dict] = []

    def rel(self, p: Path) -> str:
        try:
            return str(p.relative_to(self.root))
        except ValueError:
            return str(p)

    def add(self, signal: str, hook_type: str, event: str, idea: str, evidence: list[str], benefit: str,
            effort: str = "S", note: str = ""):
        if not evidence:
            return
        self.out.append({
            "id": f"{signal}#{len([o for o in self.out if o['signal'] == signal]) + 1}",
            "signal": signal, "type": hook_type, "event": event, "idea": idea,
            "evidence": evidence[:12], "evidence_count": len(evidence),
            "benefit": benefit, "effort": effort, "note": note,
        })

    # ------------------------------------------------------------------ scans
    def run(self) -> list[dict]:
        todo, secrets, generated, changelogs, gen_scripts = [], [], [], [], []
        deploy, locks, pyenv, dbs, markers, formatters, gitconv = [], [], [], [], [], [], []
        claude_md = []
        for d, dirnames, filenames in walk(self.root, self.depth):
            rel_dir = self.rel(d)
            in_secret_dir = bool(set(d.parts) & SECRET_DIRS)
            for name in filenames:
                p = d / name
                r = self.rel(p)
                low = name.lower()
                if name == "CLAUDE.md":
                    claude_md.append(r)
                if TODO_NAMES.match(name):
                    txt = read_text(p, 50_000)
                    n_items = len(CHECKBOX.findall(txt)) or len(NUMBERED.findall(txt))
                    fmt = "checkbox" if CHECKBOX.search(txt) else ("numerata" if NUMBERED.search(txt) else "libera")
                    todo.append(f"{r} ({n_items} voci, lista {fmt})")
                if (SECRET_NAMES.match(name) and not SECRET_EXAMPLE.search(name)) or (in_secret_dir and not SECRET_EXAMPLE.search(name)):
                    secrets.append(r)
                if low.endswith((".md", ".py", ".ts", ".tsx", ".js", ".mjs", ".json", ".yml", ".yaml", ".toml", ".sql", ".graphql", ".d.ts")) and p.stat().st_size < 5_000_000:
                    if looks_generated(head(p), low.endswith(".md")) and not name.endswith("SKILL.md"):
                        generated.append(r)
                if CHANGELOG_NAMES.match(name):
                    changelogs.append(r)
                if GEN_SCRIPT_NAMES.search(name) and low.endswith((".py", ".sh", ".mjs", ".js", ".ts")):
                    gen_scripts.append(r)
                if name in DEPLOY_FILES:
                    deploy.append(f"{r} → {DEPLOY_FILES[name]}")
                if rel_dir.startswith(".github/workflows") or "/.github/workflows" in rel_dir:
                    if re.search(r"deploy|release|publish", name, re.I):
                        deploy.append(f"{r} → GitHub Actions")
                if name in LOCKFILES:
                    locks.append(f"{r} → {LOCKFILES[name][0]}")
                if name in PY_ENV_FILES:
                    pyenv.append(f"{r} → {PY_ENV_FILES[name]}")
                if Path(low).suffix in DB_EXT:
                    dbs.append(r)
                if MARKER_NAMES.search(name) and not TODO_NAMES.match(name) and low.endswith((".md", ".json", ".txt", ".log", "")) and "log" not in rel_dir:
                    markers.append(r)
                if name in FORMATTER_FILES and FORMATTER_FILES[name]:
                    formatters.append(f"{r} → {FORMATTER_FILES[name]}")
                if name in GIT_CONVENTION_FILES:
                    gitconv.append(f"{r} → {GIT_CONVENTION_FILES[name]}")
            for dn in dirnames:
                if dn in GIT_CONVENTION_FILES:
                    gitconv.append(f"{self.rel(d / dn)} → {GIT_CONVENTION_FILES[dn]}")
                if dn in {".venv", "venv"}:
                    pyenv.append(f"{self.rel(d / dn)}/bin/python")

        pyproject = self.root / "pyproject.toml"
        if pyproject.is_file():
            t = read_text(pyproject, 20_000)
            for tool in ("ruff", "black", "isort"):
                if f"[tool.{tool}" in t:
                    formatters.append(f"pyproject.toml → {tool}")

        # --- emissione idee -------------------------------------------------
        self.add("todo-file", "D", "prompt.submit",
                 "Cattura todo senza turno del modello: `todo: <testo>` (o il prefisso che l'utente usa già) → append al file con numero/checkbox corretti, `{ drop }` con conferma. Variante: `done: <testo>` rimuove/spunta la riga.",
                 todo, "token: ogni cattura = 1 turno in meno (contesto intero risparmiato)", "S",
                 "Confermare con l'utente i prefissi accettati; se il file non esiste nella cwd l'hook lascia passare.")
        self.add("secrets", "H", "tool.call",
                 "Deny su Read/Edit/Write e su `cat|sed|grep|echo` in Bash quando il path è un file di segreti; deny su `git add` che li include. Il testo del deny dice al modello di leggere solo i NOMI delle variabili (`grep -o '^[A-Z_]*=' .env`).",
                 secrets, "rischio: segreti nel transcript/commit (irreversibile)", "S",
                 "Distinguere i file `.example`: quelli restano leggibili.")
        self.add("autogenerated", "H", "tool.call",
                 "Deny su Edit/Write dei file autogenerati (marker in testa), con nel messaggio il generatore da lanciare; per Bash, deny se path + indicatore di scrittura (`sed -i`, `>`, `tee`).",
                 generated, "tempo: niente edit persi alla prossima rigenerazione; token: zero turni di rework", "S")
        self.add("changelog-after-commit", "E", "tool.call (post `git commit`)",
                 "Dopo un `git commit` riuscito lancia in background lo script di rigenerazione (changelog/tree/indice) via `$.process.run`, oppure `$.prompt.submit('/commit-docs')` a fine turno se serve giudizio.",
                 changelogs + gen_scripts, "coerenza: documentazione mai indietro; token: il modello non deve ricordarsi il passo", "M",
                 "Solo se lo script è deterministico e veloce (< budget del dispatch): altrimenti delegare a fine turno.")
        self.add("deploy-on-push", "B", "tool.call",
                 "Prima di `git push` nella dir che fa deploy (submodule, Netlify/Vercel/Fly, workflow di release) `$.ui.ask` con due opzioni; dialogo chiuso = deny. Memoria dell'ok in `$.store` per la sessione.",
                 deploy, "rischio: deploy non voluto, quota build consumata", "S")
        self.add("package-manager", "C", "tool.call",
                 "Riscrivi `npm|yarn|npx` nel gestore del lockfile (`pnpm`, `bun`, …) prima che il comando parta; log della riscrittura con `$.ui.log`.",
                 locks, "token: niente comando fallito + retry; lockfile mai sporcato", "S",
                 "Non riscrivere dentro stringhe quotate o `grep`.")
        self.add("python-interpreter", "C", "tool.call",
                 "Riscrivi `python|python3|pip` con l'interprete dell'ambiente del progetto (venv/uv/poetry/conda) quando il comando gira dalla root.",
                 pyenv, "token: niente `ModuleNotFoundError` + retry (2-3 turni ogni volta)", "S",
                 "Verificare che l'interprete esista prima di riscrivere (`$.fs.exists`).")
        self.add("database-file", "B", "tool.call",
                 "Gate su Bash quando il comando tocca il DB con `DROP|DELETE FROM|TRUNCATE|ALTER|UPDATE` senza `WHERE`, o quando Write/Edit puntano al file del DB: `$.ui.ask` prima, deny se chiuso. Le SELECT passano.",
                 dbs, "rischio: perdita dati locale (spesso senza backup)", "M")
        self.add("status-markers", "G", "session.start + ui.render AbovePrompt",
                 "Barra sopra il prompt con lo stato dei marker/code (ultimo run del cron, voci pendenti) e un `Button` con hotkey che lancia la skill di smaltimento. Zero turni: legge i file all'avvio e a intervalli.",
                 markers, "tempo: niente 'controlla se il cron ha girato' a mano; token: niente turno per chiederlo", "M",
                 "Solo sessione interattiva; hotkey solo cifre; props dall'allowlist.")
        self.add("formatter", "E", "tool.call (post Edit/Write)",
                 "Dopo Edit/Write su un file sorgente lancia il formatter del progetto sul solo file toccato (`$.process.run(['ruff','format',path])`), senza turno.",
                 formatters, "token: il modello non spende turni per formattare o correggere lint banali", "S",
                 "Formatter, non linter con fix invasivi; escludere file generati.")
        self.add("git-conventions", "F/C", "attribution.text + tool.call",
                 "Footer/firma commit e PR da `attribution.text`; deny su `git commit --no-verify` e `git push --force` (senza `--force-with-lease`) se il repo ha pre-commit/husky/commitlint.",
                 gitconv, "coerenza: convenzioni sempre rispettate; rischio: bypass dei check", "S")

        # server MCP configurati: tool a nome distruttivo/outbound
        mcp = self.mcp_servers()
        if mcp:
            self.add("mcp-destructive-tools", "A/B", "tool.call",
                     "Per i server MCP configurati, deny (o `$.ui.ask`) sui tool il cui nome contiene delete/trash/remove/send/publish/deploy/pay: matcher regex sul nome `mcp__<server>__…`. Il messaggio dice cosa fare invece (bozza, proposta).",
                     mcp, "rischio: azione esterna irreversibile (email inviata, file cancellato, pagamento)", "S",
                     "Elencare i tool reali con `claude mcp list`/`tool.list` prima di scrivere la regex; mai un deny su nomi indovinati.")

        # limiti: altri agenti, CLAUDE.md pesante
        others = [f for f in OTHER_AGENT_FILES if (self.root / f).exists()]
        if others:
            self.add("other-agents", "N", "—",
                     "Il workspace è letto anche da agenti che NON eseguono plugin Claude Code: le regole che valgono per loro restano nel file di istruzioni in una riga, l'hook copre solo Claude Code.",
                     others, "limite, non idea", "—")
        for r in claude_md:
            size = (self.root / r).stat().st_size
            if size > 8_000:
                self.add("large-instructions", "—", "—",
                         f"`{r}` pesa {size:,} byte (~{size // 4:,} token a ogni turno): ogni regola spostata in un hook si ripaga da sola. Misura per sezione: `context_size.py {r} --by-section`.",
                         [f"{r} ({size:,} byte)"], "token: fisso, a ogni turno di ogni sessione", "—")
        return self.out

    def mcp_servers(self) -> list[str]:
        found: list[str] = []
        for p in (self.root / ".mcp.json", self.root / ".claude" / "mcp.json"):
            if p.is_file():
                try:
                    servers = json.loads(read_text(p)).get("mcpServers", {})
                    found += [f"{self.rel(p)} → {s}" for s in servers]
                except json.JSONDecodeError:
                    pass
        home = Path.home() / ".claude.json"
        if home.is_file():
            try:
                data = json.loads(read_text(home, 5_000_000))
                for s in (data.get("mcpServers") or {}):
                    found.append(f"~/.claude.json (globale) → {s}")
                proj = (data.get("projects") or {}).get(str(self.root)) or {}
                for s in (proj.get("mcpServers") or {}):
                    found.append(f"~/.claude.json (progetto) → {s}")
            except (json.JSONDecodeError, OSError):
                pass
        return found


def to_markdown(items: list[dict]) -> str:
    lines = ["| # | segnale | tipo | evento | idea | beneficio | sforzo | evidenza |", "|---|---|---|---|---|---|---|---|"]
    for i, o in enumerate(items, 1):
        ev = "; ".join(o["evidence"][:3]) + (f" (+{o['evidence_count'] - 3})" if o["evidence_count"] > 3 else "")
        idea = o["idea"].replace("|", "\\|")
        lines.append(f"| {i} | {o['signal']} | {o['type']} | {o['event']} | {idea[:160]} | {o['benefit']} | {o['effort']} | {ev} |")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="root del workspace (default: cwd)")
    ap.add_argument("--depth", type=int, default=4, help="profondità massima della scansione (default 4)")
    ap.add_argument("--out", help="scrive il JSON qui (default: stdout)")
    ap.add_argument("--md", action="store_true", help="stampa anche la tabella markdown")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    items = Finder(root, args.depth).run()
    payload = {"root": str(root), "depth": args.depth, "count": len(items), "opportunities": items}
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"{len(items)} segnali → {out}", file=sys.stderr)
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    if args.md:
        print("\n" + to_markdown(items))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
